// Theme generator for "2030".
// Each variant is defined as a compact palette of roles; this script expands
// every palette into a full VS Code color-theme file so all variants stay
// structurally identical. Run: `node build-themes.js`
const fs = require("fs");
const path = require("path");

// ---- helpers -------------------------------------------------------------
const clamp = (n) => Math.max(0, Math.min(255, Math.round(n)));
const hx = (n) => clamp(n).toString(16).padStart(2, "0");
function parse(hex) {
  const h = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
}
/** mix `hex` toward `target` by amt (0..1). */
function mix(hex, target, amt) {
  const a = parse(hex),
    b = parse(target);
  return "#" + a.map((v, i) => hx(v + (b[i] - v) * amt)).join("");
}
const lighten = (hex, amt = 0.25) => mix(hex, "#ffffff", amt);
/** append an 8-bit alpha (2-hex-digit string) to a #RRGGBB color. */
const A = (hex, aa) => hex + aa;

// ---- palettes ------------------------------------------------------------
// Every palette carries the same role keys. Aesthetic colors (accent, syntax)
// vary freely, but the *semantic* slots (error/warning/info/success) stay
// meaningful in every variant so diagnostics and git colors always read right.
const PALETTES = [
  {
    file: "2030",
    name: "2030",
    ui: "vs-dark",
    type: "dark",
    bg: "#0A0D14", bgDeep: "#080A10", bgPanel: "#0D1119", bgLine: "#11151F", bgLift: "#161C2A",
    fg: "#C6D2E2", fgMuted: "#7A88A0", fgFaint: "#5A6680", fgSubtle: "#3D4A63", lineNr: "#33405A",
    border: "#11151F", borderSoft: "#1A2030", sel: "#2B4A66",
    accent: "#34F5C5", accent2: "#FF4D9D",
    comment: "#445069", keyword: "#FF4D9D", storage: "#FF7AB8", string: "#34F5C5", stringAlt: "#5EFFD7",
    escape: "#FFD93D", number: "#FFB84D", boolean: "#FF7A5C", constant: "#FFB84D",
    func: "#5BC0FF", funcDecl: "#7DD3FF", klass: "#C792FF", iface: "#A8E0FF", variable: "#C6D2E2",
    parameter: "#FFAFA0", property: "#9BD8FF", langVar: "#FF7A5C", operator: "#6EE7FF", punct: "#5A6680",
    tag: "#FF4D9D", attribute: "#FFD93D", regexp: "#FF7AB8",
    error: "#FF3B5C", warning: "#FFB84D", info: "#5BC0FF", success: "#34F5C5",
  },
  {
    file: "2030-void",
    name: "2030 Void",
    ui: "vs-dark",
    type: "dark",
    bg: "#000000", bgDeep: "#000000", bgPanel: "#05070B", bgLine: "#0B0E15", bgLift: "#10151F",
    fg: "#C6D2E2", fgMuted: "#7A88A0", fgFaint: "#5A6680", fgSubtle: "#3D4A63", lineNr: "#2E3A52",
    border: "#0B0E15", borderSoft: "#141A28", sel: "#2B4A66",
    accent: "#34F5C5", accent2: "#FF4D9D",
    comment: "#445069", keyword: "#FF4D9D", storage: "#FF7AB8", string: "#34F5C5", stringAlt: "#5EFFD7",
    escape: "#FFD93D", number: "#FFB84D", boolean: "#FF7A5C", constant: "#FFB84D",
    func: "#5BC0FF", funcDecl: "#7DD3FF", klass: "#C792FF", iface: "#A8E0FF", variable: "#C6D2E2",
    parameter: "#FFAFA0", property: "#9BD8FF", langVar: "#FF7A5C", operator: "#6EE7FF", punct: "#5A6680",
    tag: "#FF4D9D", attribute: "#FFD93D", regexp: "#FF7AB8",
    error: "#FF3B5C", warning: "#FFB84D", info: "#5BC0FF", success: "#34F5C5",
  },
  {
    file: "2030-daylight",
    name: "2030 Daylight",
    ui: "vs",
    type: "light",
    bg: "#FBFCFE", bgDeep: "#F2F5FA", bgPanel: "#FFFFFF", bgLine: "#EEF2F9", bgLift: "#E3EAF5",
    fg: "#1E2738", fgMuted: "#5A6A82", fgFaint: "#8A97AC", fgSubtle: "#AEB9CC", lineNr: "#B4BECE",
    border: "#E1E7F0", borderSoft: "#D3DBE8", sel: "#A9D5F2",
    accent: "#0E9E84", accent2: "#D6247E",
    comment: "#8A97AC", keyword: "#D6247E", storage: "#C13A8A", string: "#0E9E84", stringAlt: "#0BB393",
    escape: "#C79100", number: "#C77400", boolean: "#D6533A", constant: "#C77400",
    func: "#1273C9", funcDecl: "#0E63B0", klass: "#8A4FD6", iface: "#4F7FD6", variable: "#1E2738",
    parameter: "#C15A4A", property: "#2A6FB0", langVar: "#D6533A", operator: "#0E8FB0", punct: "#8A97AC",
    tag: "#D6247E", attribute: "#B08900", regexp: "#C13A8A",
    error: "#D62839", warning: "#C77400", info: "#1273C9", success: "#0E9E84",
  },
  {
    file: "2030-solar",
    name: "2030 Solar",
    ui: "vs-dark",
    type: "dark",
    // warm ember terminal — amber, gold, coral on charcoal
    bg: "#14100A", bgDeep: "#100C07", bgPanel: "#191309", bgLine: "#1E170D", bgLift: "#2A2012",
    fg: "#F0E0C8", fgMuted: "#A89476", fgFaint: "#7A6A50", fgSubtle: "#574A38", lineNr: "#4A3D2A",
    border: "#1E170D", borderSoft: "#2C2416", sel: "#5A3D1F",
    accent: "#FFB454", accent2: "#FF6B4A",
    comment: "#6B5A42", keyword: "#FF6B4A", storage: "#FF8A6B", string: "#E8C15A", stringAlt: "#FFD98A",
    escape: "#FFE08A", number: "#FF9E4A", boolean: "#FF5C7A", constant: "#FF9E4A",
    func: "#FFC978", funcDecl: "#FFD98A", klass: "#FF9AC0", iface: "#FFB0D0", variable: "#F0E0C8",
    parameter: "#E0A882", property: "#FFCF9E", langVar: "#FF5C7A", operator: "#FFC96B", punct: "#7A6A50",
    tag: "#FF6B4A", attribute: "#FFE08A", regexp: "#FF8A6B",
    error: "#FF4D4D", warning: "#FF9E4A", info: "#FFC978", success: "#C8D14A",
  },
  {
    file: "2030-synthwave",
    name: "2030 Synthwave",
    ui: "vs-dark",
    type: "dark",
    // retro 80s — hot magenta, cyan, purple, sunny yellow on deep indigo
    bg: "#17132E", bgDeep: "#120F26", bgPanel: "#1D1838", bgLine: "#241E44", bgLift: "#302856",
    fg: "#E0D4FF", fgMuted: "#9A8AC8", fgFaint: "#6E5F9E", fgSubtle: "#4E4176", lineNr: "#453A6E",
    border: "#241E44", borderSoft: "#322A5A", sel: "#46367E",
    accent: "#FF3CA6", accent2: "#00E5FF",
    comment: "#5E5290", keyword: "#FF3CA6", storage: "#FF6EC7", string: "#FFD866", stringAlt: "#FFE58A",
    escape: "#FF8CC6", number: "#FF8B6B", boolean: "#FF6EC7", constant: "#FF8B6B",
    func: "#00E5FF", funcDecl: "#6BF0FF", klass: "#C77DFF", iface: "#A88BFF", variable: "#E0D4FF",
    parameter: "#FF9EDC", property: "#7DE0FF", langVar: "#FF6EC7", operator: "#72F1FF", punct: "#6E5F9E",
    tag: "#FF3CA6", attribute: "#FFD866", regexp: "#FF8CC6",
    error: "#FF4D6D", warning: "#FFB454", info: "#00E5FF", success: "#36F9C6",
  },
  {
    file: "2030-matrix",
    name: "2030 Matrix",
    ui: "vs-dark",
    type: "dark",
    // green phosphor CRT — near-mono green on black (errors stay red for readability)
    bg: "#030805", bgDeep: "#010402", bgPanel: "#071009", bgLine: "#0A170D", bgLift: "#103018",
    fg: "#7CFFA0", fgMuted: "#4F9E68", fgFaint: "#367A48", fgSubtle: "#245234", lineNr: "#2A5E38",
    border: "#0A170D", borderSoft: "#123018", sel: "#1E5C30",
    accent: "#00FF66", accent2: "#7CFFA0",
    comment: "#2F6B40", keyword: "#00FF9C", storage: "#4DFFA6", string: "#B6FF6B", stringAlt: "#D4FF9A",
    escape: "#E0FF8A", number: "#E8FF7A", boolean: "#6BFFB0", constant: "#E8FF7A",
    func: "#35FFB0", funcDecl: "#6BFFC8", klass: "#9EFF6B", iface: "#B6FF9A", variable: "#7CFFA0",
    parameter: "#A6FFB8", property: "#5AFFA0", langVar: "#6BFFB0", operator: "#4DFFCA", punct: "#367A48",
    tag: "#00FF9C", attribute: "#E0FF8A", regexp: "#4DFFA6",
    error: "#FF5C5C", warning: "#E8FF7A", info: "#35FFB0", success: "#00FF66",
  },
  {
    file: "2030-aurora",
    name: "2030 Aurora",
    ui: "vs-dark",
    type: "dark",
    // cool arctic — teal, ice-blue, periwinkle, lavender on deep slate
    bg: "#0A1420", bgDeep: "#07101A", bgPanel: "#0E1B29", bgLine: "#132434", bgLift: "#1B3346",
    fg: "#CFE6F5", fgMuted: "#7C97AD", fgFaint: "#567488", fgSubtle: "#3E5C70", lineNr: "#365060",
    border: "#132434", borderSoft: "#1E3345", sel: "#24506E",
    accent: "#4FE3D0", accent2: "#7AA5FF",
    comment: "#47657A", keyword: "#7AA5FF", storage: "#9DBEFF", string: "#4FE3D0", stringAlt: "#7FF0E0",
    escape: "#A0E8FF", number: "#6BD5FF", boolean: "#8ED0C0", constant: "#6BD5FF",
    func: "#5BB8FF", funcDecl: "#8ACDFF", klass: "#B79DFF", iface: "#C9BAFF", variable: "#CFE6F5",
    parameter: "#90C8D8", property: "#9BDFF0", langVar: "#8ED0C0", operator: "#6EE7FF", punct: "#567488",
    tag: "#7AA5FF", attribute: "#A0E8FF", regexp: "#9DBEFF",
    error: "#FF6B7D", warning: "#FFC46B", info: "#5BB8FF", success: "#4FE3D0",
  },
];

// ---- expansion -----------------------------------------------------------
function build(p) {
  const isLight = p.type === "light";
  const lift = (hex, amt = 0.22) => (isLight ? mix(hex, "#000000", amt * 0.7) : lighten(hex, amt));
  const onAccent = isLight ? "#FFFFFF" : p.bg; // fg placed on top of an accent fill
  return {
    $schema: "vscode://schemas/color-theme",
    name: p.name,
    type: p.type,
    semanticHighlighting: true,
    colors: {
      "//": "===== EDITOR CORE =====",
      "editor.background": p.bg,
      "editor.foreground": p.fg,
      "editorCursor.foreground": p.accent,
      "editorCursor.background": p.bg,
      "editor.lineHighlightBackground": p.bgLine,
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": A(p.sel, "55"),
      "editor.selectionHighlightBackground": A(p.sel, "33"),
      "editor.inactiveSelectionBackground": A(p.sel, "30"),
      "editor.wordHighlightBackground": A(p.info, "22"),
      "editor.wordHighlightStrongBackground": A(p.accent, "22"),
      "editor.findMatchBackground": A(p.warning, "55"),
      "editor.findMatchHighlightBackground": A(p.warning, "2A"),
      "editor.findRangeHighlightBackground": A(p.sel, "22"),
      "editor.hoverHighlightBackground": A(p.info, "1A"),
      "editor.rangeHighlightBackground": p.bgLine,
      "editorLineNumber.foreground": p.lineNr,
      "editorLineNumber.activeForeground": p.accent,
      "editorIndentGuide.background1": p.borderSoft,
      "editorIndentGuide.activeBackground1": A(p.accent, "44"),
      "editorWhitespace.foreground": p.borderSoft,
      "editorRuler.foreground": p.borderSoft,
      "editorBracketMatch.background": A(p.accent, "22"),
      "editorBracketMatch.border": A(p.accent, "AA"),

      "//1": "===== BRACKET PAIR COLORS (rainbow) =====",
      "editorBracketHighlight.foreground1": p.accent2,
      "editorBracketHighlight.foreground2": p.func,
      "editorBracketHighlight.foreground3": p.accent,
      "editorBracketHighlight.foreground4": p.number,
      "editorBracketHighlight.foreground5": p.klass,
      "editorBracketHighlight.foreground6": p.boolean,
      "editorBracketHighlight.unexpectedBracket.foreground": p.error,

      "//2": "===== GUTTER / GIT =====",
      "editorGutter.background": p.bg,
      "editorGutter.modifiedBackground": p.info,
      "editorGutter.addedBackground": p.success,
      "editorGutter.deletedBackground": p.error,
      "editorError.foreground": p.error,
      "editorWarning.foreground": p.warning,
      "editorInfo.foreground": p.info,
      "editorHint.foreground": p.accent,

      "//3": "===== WORKBENCH SHELL =====",
      foreground: p.fg,
      focusBorder: A(p.accent, "66"),
      "selection.background": A(p.accent, "44"),
      errorForeground: p.error,
      descriptionForeground: p.fgMuted,
      "icon.foreground": p.fgMuted,
      "widget.shadow": "#00000088",
      "editorWidget.background": p.bgPanel,
      "editorWidget.border": p.borderSoft,
      "editorSuggestWidget.background": p.bgPanel,
      "editorSuggestWidget.border": p.borderSoft,
      "editorSuggestWidget.foreground": p.fg,
      "editorSuggestWidget.highlightForeground": p.accent,
      "editorSuggestWidget.selectedBackground": p.bgLift,
      "editorHoverWidget.background": p.bgPanel,
      "editorHoverWidget.border": p.borderSoft,

      "//4": "===== SIDEBAR =====",
      "sideBar.background": p.bgDeep,
      "sideBar.foreground": isLight ? p.fgMuted : "#9AA8C0",
      "sideBar.border": p.border,
      "sideBarTitle.foreground": p.accent,
      "sideBarSectionHeader.background": p.bg,
      "sideBarSectionHeader.foreground": p.fgMuted,
      "sideBarSectionHeader.border": p.border,
      "list.activeSelectionBackground": p.bgLift,
      "list.activeSelectionForeground": p.accent,
      "list.inactiveSelectionBackground": p.bgLine,
      "list.inactiveSelectionForeground": p.fg,
      "list.hoverBackground": p.bgLine,
      "list.hoverForeground": p.fg,
      "list.focusBackground": p.bgLift,
      "list.highlightForeground": p.accent,
      "list.errorForeground": p.error,
      "list.warningForeground": p.warning,
      "tree.indentGuidesStroke": p.borderSoft,

      "//5": "===== ACTIVITY BAR =====",
      "activityBar.background": p.bgDeep,
      "activityBar.foreground": p.accent,
      "activityBar.inactiveForeground": p.fgSubtle,
      "activityBar.border": p.border,
      "activityBarBadge.background": p.accent2,
      "activityBarBadge.foreground": onAccent,
      "activityBar.activeBorder": p.accent,
      "activityBar.activeBackground": p.bgPanel,

      "//6": "===== STATUS BAR =====",
      "statusBar.background": p.bgDeep,
      "statusBar.foreground": p.fgMuted,
      "statusBar.border": p.border,
      "statusBar.noFolderBackground": p.bgDeep,
      "statusBar.debuggingBackground": p.accent2,
      "statusBar.debuggingForeground": onAccent,
      "statusBarItem.remoteBackground": p.accent,
      "statusBarItem.remoteForeground": onAccent,
      "statusBarItem.hoverBackground": p.bgLift,
      "statusBarItem.prominentBackground": p.accent2,
      "statusBarItem.prominentForeground": onAccent,

      "//7": "===== TITLE BAR =====",
      "titleBar.activeBackground": p.bgDeep,
      "titleBar.activeForeground": p.fg,
      "titleBar.inactiveBackground": p.bgDeep,
      "titleBar.inactiveForeground": p.fgSubtle,
      "titleBar.border": p.border,

      "//8": "===== TABS =====",
      "editorGroupHeader.tabsBackground": p.bgDeep,
      "editorGroupHeader.tabsBorder": p.border,
      "editorGroup.border": p.border,
      "tab.activeBackground": p.bg,
      "tab.activeForeground": p.accent,
      "tab.activeBorderTop": p.accent,
      "tab.activeBorder": "#00000000",
      "tab.inactiveBackground": p.bgDeep,
      "tab.inactiveForeground": p.fgFaint,
      "tab.border": p.border,
      "tab.hoverBackground": p.bgPanel,
      "tab.hoverForeground": p.fg,
      "tab.unfocusedActiveForeground": p.fgMuted,
      "tab.activeModifiedBorder": p.warning,

      "//9": "===== PANEL / TERMINAL =====",
      "panel.background": p.bgDeep,
      "panel.border": p.border,
      "panelTitle.activeForeground": p.accent,
      "panelTitle.activeBorder": p.accent,
      "panelTitle.inactiveForeground": p.fgFaint,
      "terminal.background": p.bgDeep,
      "terminal.foreground": p.fg,
      "terminalCursor.foreground": p.accent,
      "terminalCursor.background": p.bgDeep,
      "terminal.selectionBackground": A(p.sel, "55"),
      "terminal.ansiBlack": p.borderSoft,
      "terminal.ansiRed": p.error,
      "terminal.ansiGreen": p.success,
      "terminal.ansiYellow": p.number,
      "terminal.ansiBlue": p.info,
      "terminal.ansiMagenta": p.accent2,
      "terminal.ansiCyan": p.operator,
      "terminal.ansiWhite": p.fg,
      "terminal.ansiBrightBlack": p.fgSubtle,
      "terminal.ansiBrightRed": lighten(p.error, 0.2),
      "terminal.ansiBrightGreen": lighten(p.success, 0.2),
      "terminal.ansiBrightYellow": lighten(p.number, 0.2),
      "terminal.ansiBrightBlue": lighten(p.info, 0.2),
      "terminal.ansiBrightMagenta": lighten(p.accent2, 0.2),
      "terminal.ansiBrightCyan": lighten(p.operator, 0.2),
      "terminal.ansiBrightWhite": isLight ? p.fg : "#FFFFFF",

      "//10": "===== INPUTS / BUTTONS =====",
      "input.background": p.bgPanel,
      "input.foreground": p.fg,
      "input.border": p.borderSoft,
      "input.placeholderForeground": p.fgFaint,
      "inputOption.activeBorder": p.accent,
      "inputOption.activeBackground": A(p.accent, "22"),
      "inputValidation.errorBackground": isLight ? "#FDECEE" : "#2A0F16",
      "inputValidation.errorBorder": p.error,
      "button.background": p.accent,
      "button.foreground": onAccent,
      "button.hoverBackground": lift(p.accent),
      "button.secondaryBackground": p.bgLift,
      "button.secondaryForeground": p.fg,
      "badge.background": p.accent2,
      "badge.foreground": onAccent,
      "progressBar.background": p.accent,

      "//11": "===== SCROLLBAR =====",
      "scrollbar.shadow": "#00000066",
      "scrollbarSlider.background": A(p.borderSoft, "88"),
      "scrollbarSlider.hoverBackground": A(p.sel, "AA"),
      "scrollbarSlider.activeBackground": A(p.accent, "66"),

      "//12": "===== GIT DECORATIONS =====",
      "gitDecoration.modifiedResourceForeground": p.info,
      "gitDecoration.deletedResourceForeground": p.error,
      "gitDecoration.untrackedResourceForeground": p.success,
      "gitDecoration.ignoredResourceForeground": p.fgSubtle,
      "gitDecoration.conflictingResourceForeground": p.warning,
      "gitDecoration.addedResourceForeground": p.success,

      "//13": "===== DIFF =====",
      "diffEditor.insertedTextBackground": A(p.success, "1A"),
      "diffEditor.removedTextBackground": A(p.error, "1A"),
      "diffEditor.insertedLineBackground": A(p.success, "14"),
      "diffEditor.removedLineBackground": A(p.error, "14"),

      "//14": "===== MISC =====",
      "peekView.border": p.accent,
      "peekViewEditor.background": p.bgPanel,
      "peekViewResult.background": p.bgDeep,
      "peekViewTitle.background": p.bgPanel,
      "breadcrumb.foreground": p.fgFaint,
      "breadcrumb.focusForeground": p.accent,
      "breadcrumb.activeSelectionForeground": p.accent,
      "breadcrumbPicker.background": p.bgPanel,
      "menu.background": p.bgPanel,
      "menu.foreground": p.fg,
      "menu.selectionBackground": p.bgLift,
      "menu.selectionForeground": p.accent,
      "menu.border": p.borderSoft,
      "quickInput.background": p.bgPanel,
      "quickInputList.focusBackground": p.bgLift,
      "quickInputList.focusForeground": p.accent,
      "notificationCenterHeader.background": p.bgPanel,
      "notifications.background": p.bgPanel,
      "notifications.border": p.borderSoft,
      "editorOverviewRuler.border": p.border,
      "minimap.selectionHighlight": A(p.accent, "66"),

      "//15": "===== STICKY SCROLL =====",
      "editorStickyScroll.background": p.bg,
      "editorStickyScroll.border": p.border,
      "editorStickyScrollHover.background": p.bgLine,
      "editorStickyScroll.shadow": "#00000066",

      "//16": "===== INLAY HINTS =====",
      "editorInlayHint.foreground": p.fgFaint,
      "editorInlayHint.background": A(p.bgLine, "88"),
      "editorInlayHint.typeForeground": p.klass,
      "editorInlayHint.typeBackground": A(p.bgLine, "88"),
      "editorInlayHint.parameterForeground": p.parameter,
      "editorInlayHint.parameterBackground": A(p.bgLine, "88"),

      "//17": "===== GHOST TEXT / INLINE SUGGEST (AI) =====",
      "editorGhostText.foreground": p.comment,
      "editorGhostText.border": "#00000000",
      "editorGhostText.background": "#00000000",

      "//18": "===== BRACKET PAIR GUIDES =====",
      "editorBracketPairGuide.background1": A(p.accent2, "44"),
      "editorBracketPairGuide.background2": A(p.func, "44"),
      "editorBracketPairGuide.background3": A(p.accent, "44"),
      "editorBracketPairGuide.background4": A(p.number, "44"),
      "editorBracketPairGuide.background5": A(p.klass, "44"),
      "editorBracketPairGuide.background6": A(p.boolean, "44"),
      "editorBracketPairGuide.activeBackground1": p.accent2,
      "editorBracketPairGuide.activeBackground2": p.func,
      "editorBracketPairGuide.activeBackground3": p.accent,
      "editorBracketPairGuide.activeBackground4": p.number,
      "editorBracketPairGuide.activeBackground5": p.klass,
      "editorBracketPairGuide.activeBackground6": p.boolean,

      "//19": "===== CODE LENS / LIGHT BULB / FOLDING / LINKS =====",
      "editorCodeLens.foreground": p.fgFaint,
      "editorLightBulb.foreground": p.escape,
      "editorLightBulbAutoFix.foreground": p.accent,
      "editor.foldBackground": A(p.info, "14"),
      "editorLink.activeForeground": p.operator,
      "editorUnnecessaryCode.opacity": "#FFFFFF77",
      "editorGutter.commentRangeForeground": p.fgFaint,

      "//20": "===== OVERVIEW RULER MARKERS =====",
      "editorOverviewRuler.findMatchForeground": A(p.warning, "88"),
      "editorOverviewRuler.errorForeground": p.error,
      "editorOverviewRuler.warningForeground": p.warning,
      "editorOverviewRuler.infoForeground": p.info,
      "editorOverviewRuler.modifiedForeground": p.info,
      "editorOverviewRuler.addedForeground": p.success,
      "editorOverviewRuler.deletedForeground": p.error,
      "editorOverviewRuler.bracketMatchForeground": A(p.accent, "AA"),
      "editorOverviewRuler.wordHighlightForeground": A(p.info, "66"),
      "editorOverviewRuler.selectionHighlightForeground": A(p.accent, "66"),

      "//21": "===== MINIMAP =====",
      "minimap.findMatchHighlight": A(p.warning, "AA"),
      "minimap.errorHighlight": A(p.error, "AA"),
      "minimap.warningHighlight": A(p.warning, "AA"),
      "minimapSlider.background": A(p.borderSoft, "55"),
      "minimapSlider.hoverBackground": A(p.sel, "77"),
      "minimapSlider.activeBackground": A(p.accent, "44"),
      "minimapGutter.addedBackground": p.success,
      "minimapGutter.modifiedBackground": p.info,
      "minimapGutter.deletedBackground": p.error,

      "//22": "===== MERGE CONFLICTS =====",
      "merge.currentHeaderBackground": A(p.success, "44"),
      "merge.currentContentBackground": A(p.success, "1A"),
      "merge.incomingHeaderBackground": A(p.info, "44"),
      "merge.incomingContentBackground": A(p.info, "1A"),
      "merge.commonHeaderBackground": A(p.warning, "44"),
      "merge.commonContentBackground": A(p.warning, "1A"),
      "merge.border": "#00000000",
      "mergeEditor.change.background": A(p.success, "1A"),
      "mergeEditor.change.word.background": A(p.success, "33"),
      "mergeEditor.conflict.unhandledUnfocused.border": A(p.warning, "66"),
      "mergeEditor.conflict.unhandledFocused.border": p.warning,
      "mergeEditor.conflict.handledUnfocused.border": A(p.success, "44"),
      "mergeEditor.conflict.handledFocused.border": p.success,

      "//23": "===== NOTEBOOK =====",
      "notebook.editorBackground": p.bg,
      "notebook.cellEditorBackground": p.bgPanel,
      "notebook.cellBorderColor": p.border,
      "notebook.cellHoverBackground": p.bgPanel,
      "notebook.focusedCellBorder": A(p.accent, "66"),
      "notebook.focusedEditorBorder": A(p.accent, "66"),
      "notebook.selectedCellBackground": p.bgLine,
      "notebook.cellToolbarSeparator": p.borderSoft,
      "notebookStatusSuccessIcon.foreground": p.success,
      "notebookStatusErrorIcon.foreground": p.error,

      "//24": "===== COMMAND CENTER / BANNER =====",
      "commandCenter.background": p.bgPanel,
      "commandCenter.foreground": p.fg,
      "commandCenter.border": p.borderSoft,
      "commandCenter.activeBackground": p.bgLift,
      "commandCenter.activeForeground": p.accent,
      "commandCenter.activeBorder": A(p.accent, "66"),
      "commandCenter.inactiveForeground": p.fgFaint,
      "commandCenter.inactiveBorder": p.border,
      "banner.background": p.bgLine,
      "banner.foreground": p.fg,
      "banner.iconForeground": p.accent,

      "//25": "===== CHARTS =====",
      "charts.foreground": p.fg,
      "charts.lines": p.borderSoft,
      "charts.red": p.error,
      "charts.blue": p.info,
      "charts.yellow": p.number,
      "charts.orange": p.boolean,
      "charts.green": p.success,
      "charts.purple": p.klass,

      "//26": "===== TESTING / DEBUG =====",
      "testing.iconPassed": p.success,
      "testing.iconFailed": p.error,
      "testing.iconErrored": p.error,
      "testing.iconSkipped": p.fgFaint,
      "testing.iconQueued": p.warning,
      "debugIcon.breakpointForeground": p.accent2,
      "debugIcon.breakpointCurrentStackframeForeground": p.warning,
      "debugIcon.startForeground": p.success,
      "debugConsole.infoForeground": p.info,
      "debugConsole.errorForeground": p.error,
      "debugConsole.warningForeground": p.warning,
      "debugConsole.sourceForeground": p.klass,

      "//27": "===== KEYBINDING LABELS / SASH =====",
      "keybindingLabel.background": p.bgLine,
      "keybindingLabel.foreground": p.property,
      "keybindingLabel.border": p.borderSoft,
      "keybindingLabel.bottomBorder": p.borderSoft,
      "sash.hoverBorder": p.accent,

      "//28": "===== SYMBOL ICONS (suggest widget) =====",
      "symbolIcon.functionForeground": p.func,
      "symbolIcon.methodForeground": p.func,
      "symbolIcon.classForeground": p.klass,
      "symbolIcon.interfaceForeground": p.iface,
      "symbolIcon.variableForeground": p.variable,
      "symbolIcon.propertyForeground": p.property,
      "symbolIcon.keywordForeground": p.keyword,
      "symbolIcon.enumeratorForeground": p.number,
      "symbolIcon.constantForeground": p.constant,
      "symbolIcon.stringForeground": p.string,
    },
    tokenColors: [
      { name: "Comments", scope: ["comment", "punctuation.definition.comment", "string.comment"], settings: { foreground: p.comment, fontStyle: "italic" } },
      { name: "Keywords / control flow", scope: ["keyword", "keyword.control", "keyword.other", "storage.type.function.arrow", "punctuation.definition.keyword"], settings: { foreground: p.keyword } },
      { name: "Storage / modifiers", scope: ["storage", "storage.type", "storage.modifier"], settings: { foreground: p.storage, fontStyle: "italic" } },
      { name: "Strings", scope: ["string", "string.quoted", "punctuation.definition.string"], settings: { foreground: p.string } },
      { name: "Template / interpolation strings", scope: ["string.template", "string.interpolated"], settings: { foreground: p.stringAlt } },
      { name: "Escape characters", scope: ["constant.character.escape", "constant.character"], settings: { foreground: p.escape } },
      { name: "Numbers", scope: ["constant.numeric", "constant.numeric.integer", "constant.numeric.float"], settings: { foreground: p.number } },
      { name: "Booleans / language constants", scope: ["constant.language", "constant.language.boolean", "constant.language.null"], settings: { foreground: p.boolean, fontStyle: "bold" } },
      { name: "Constants / enum members", scope: ["constant.other", "variable.other.constant", "entity.name.constant"], settings: { foreground: p.constant } },
      { name: "Functions / method calls", scope: ["entity.name.function", "support.function", "meta.function-call", "variable.function"], settings: { foreground: p.func } },
      { name: "Function declarations", scope: ["entity.name.function.member", "meta.definition.function entity.name.function"], settings: { foreground: p.funcDecl } },
      { name: "Classes / types", scope: ["entity.name.type", "entity.name.class", "support.class", "support.type", "entity.other.inherited-class", "entity.name.namespace"], settings: { foreground: p.klass } },
      { name: "Built-in types / primitives", scope: ["support.type.primitive", "keyword.type", "storage.type.built-in"], settings: { foreground: p.klass, fontStyle: "italic" } },
      { name: "Variables", scope: ["variable", "variable.other", "variable.other.readwrite"], settings: { foreground: p.variable } },
      { name: "Parameters", scope: ["variable.parameter", "meta.parameter"], settings: { foreground: p.parameter, fontStyle: "italic" } },
      { name: "Object keys / properties", scope: ["variable.other.property", "variable.other.object.property", "support.type.property-name", "meta.object-literal.key"], settings: { foreground: p.property } },
      { name: "Language built-in variables", scope: ["variable.language", "variable.language.this", "variable.language.super"], settings: { foreground: p.langVar, fontStyle: "italic" } },
      { name: "Operators", scope: ["keyword.operator", "storage.type.operator"], settings: { foreground: p.operator } },
      { name: "Punctuation / delimiters", scope: ["punctuation", "punctuation.separator", "punctuation.terminator", "meta.brace"], settings: { foreground: p.punct } },
      { name: "HTML / XML tags", scope: ["entity.name.tag", "punctuation.definition.tag"], settings: { foreground: p.tag } },
      { name: "HTML attributes", scope: ["entity.other.attribute-name"], settings: { foreground: p.attribute, fontStyle: "italic" } },
      { name: "CSS properties", scope: ["support.type.property-name.css", "support.type.property-name.scss"], settings: { foreground: p.func } },
      { name: "CSS values / units", scope: ["support.constant.property-value.css", "keyword.other.unit.css"], settings: { foreground: p.string } },
      { name: "CSS classes / ids", scope: ["entity.other.attribute-name.class.css", "entity.other.attribute-name.id.css"], settings: { foreground: p.klass } },
      { name: "JSON keys", scope: ["support.type.property-name.json"], settings: { foreground: p.func } },
      { name: "Markdown headings", scope: ["markup.heading", "entity.name.section.markdown"], settings: { foreground: p.keyword, fontStyle: "bold" } },
      { name: "Markdown bold", scope: ["markup.bold"], settings: { foreground: p.number, fontStyle: "bold" } },
      { name: "Markdown italic", scope: ["markup.italic"], settings: { foreground: p.string, fontStyle: "italic" } },
      { name: "Markdown links", scope: ["markup.underline.link", "string.other.link.title.markdown"], settings: { foreground: p.info, fontStyle: "underline" } },
      { name: "Markdown code / inline code", scope: ["markup.inline.raw", "markup.fenced_code.block"], settings: { foreground: p.stringAlt } },
      { name: "Markdown quotes", scope: ["markup.quote"], settings: { foreground: p.fgMuted, fontStyle: "italic" } },
      { name: "Decorators / annotations", scope: ["meta.decorator", "punctuation.decorator", "entity.name.function.decorator"], settings: { foreground: p.attribute, fontStyle: "italic" } },
      { name: "Regular expressions", scope: ["string.regexp", "constant.other.character-class.regexp"], settings: { foreground: p.regexp } },
      { name: "Support / library functions", scope: ["support.function.builtin", "support.constant"], settings: { foreground: p.operator } },
      { name: "Invalid / deprecated", scope: ["invalid", "invalid.illegal"], settings: { foreground: p.error, fontStyle: "underline" } },
      { name: "Imports / module paths", scope: ["keyword.control.import", "keyword.control.from", "keyword.control.export"], settings: { foreground: p.keyword, fontStyle: "italic" } },
    ],
    semanticTokenColors: {
      namespace: p.klass,
      class: p.klass,
      "class.declaration": p.klass,
      interface: p.iface,
      enum: p.klass,
      enumMember: p.number,
      type: p.klass,
      typeParameter: { foreground: p.klass, fontStyle: "italic" },
      struct: p.klass,
      function: p.func,
      "function.declaration": p.funcDecl,
      method: p.func,
      macro: p.escape,
      variable: p.variable,
      "variable.readonly": p.constant,
      "variable.declaration": p.variable,
      parameter: { foreground: p.parameter, fontStyle: "italic" },
      property: p.property,
      "property.readonly": p.constant,
      keyword: p.keyword,
      string: p.string,
      number: p.number,
      operator: p.operator,
      decorator: p.attribute,
      "*.deprecated": { strikethrough: true },
    },
  };
}

// ---- write ---------------------------------------------------------------
const outDir = path.join(__dirname, "themes");
fs.mkdirSync(outDir, { recursive: true });
for (const p of PALETTES) {
  const file = path.join(outDir, `${p.file}-color-theme.json`);
  fs.writeFileSync(file, JSON.stringify(build(p), null, 2) + "\n", "utf8");
  console.log("wrote", path.relative(__dirname, file), "—", p.name);
}
console.log(`\n${PALETTES.length} theme variants generated.`);
