// Neon Terminal 2030 — companion extension
// Adds a neon settings panel that wires up recommended editor settings,
// theme variants, and the optional CSS glow add-on.
const vscode = require("vscode");
const fs = require("fs");
const path = require("path");

const CUSTOM_CSS_EXT = "be5invis.vscode-custom-css";

const VARIANTS = [
  { id: "Neon Terminal 2030", label: "Neon Terminal 2030", swatch: "#0A0D14" },
  { id: "Neon Terminal 2030 (Deep Void)", label: "Deep Void (OLED)", swatch: "#000000" },
  { id: "Neon Terminal 2030 (Daylight)", label: "Daylight (Light)", swatch: "#FBFCFE" },
];

const ACCENTS = [
  { id: "mint", label: "Mint", color: "#34F5C5" },
  { id: "magenta", label: "Magenta", color: "#FF4D9D" },
  { id: "sky", label: "Sky", color: "#5BC0FF" },
  { id: "violet", label: "Violet", color: "#C792FF" },
  { id: "amber", label: "Amber", color: "#FFB84D" },
];

const RECOMMENDED = {
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": "active",
  "editor.semanticHighlighting.enabled": true,
  "editor.fontLigatures": true,
  "editor.stickyScroll.enabled": true,
  "editor.inlayHints.enabled": "onUnlessPressed",
  "editor.cursorBlinking": "phase",
  "editor.cursorSmoothCaretAnimation": "on",
  "editor.smoothScrolling": true,
};

/** Build the glow stylesheet from the user's chosen knobs. */
function generateGlowCss({ strength, radius, accent }) {
  const accentHex = (ACCENTS.find((a) => a.id === accent) || ACCENTS[0]).color;
  return `/* Generated by Neon Terminal 2030 settings panel — do not edit by hand. */
:root {
  --neon-glow-strength: ${strength};
  --neon-glow-radius: ${radius}px;
  --neon-accent: ${accentHex};
  --neon-magenta: #FF4D9D;
}
.monaco-editor .view-line span {
  text-shadow: 0 0 calc(var(--neon-glow-radius) * var(--neon-glow-strength)) currentColor;
}
.monaco-editor .mtki { text-shadow: none; }
.monaco-editor .cursor {
  box-shadow: 0 0 4px var(--neon-accent), 0 0 12px var(--neon-accent), 0 0 20px var(--neon-accent);
  animation: neon-cursor-pulse 1.4s ease-in-out infinite;
}
@keyframes neon-cursor-pulse { 0%,100%{opacity:1;} 50%{opacity:.45;} }
.monaco-editor .line-numbers.active-line-number { text-shadow: 0 0 8px var(--neon-accent); }
.monaco-workbench .activitybar .active-item-indicator::before {
  box-shadow: 0 0 8px var(--neon-accent), 0 0 16px var(--neon-accent);
}
.monaco-workbench .statusbar .statusbar-item.has-background-color { box-shadow: 0 0 10px var(--neon-magenta); }
.monaco-workbench .tab.active { box-shadow: inset 0 -2px 10px -4px var(--neon-accent); }
.monaco-list .monaco-list-row.focused { box-shadow: inset 2px 0 0 0 var(--neon-accent); }
.monaco-editor .suggest-widget, .monaco-editor .monaco-hover { box-shadow: 0 0 24px -8px var(--neon-accent); }
.monaco-editor .findMatch { box-shadow: 0 0 8px -2px #FFB84D; }
`;
}

function glowCssPath(context) {
  return path.join(context.globalStorageUri.fsPath, "neon-glow.generated.css");
}

async function applyRecommended() {
  const cfg = vscode.workspace.getConfiguration();
  for (const [key, value] of Object.entries(RECOMMENDED)) {
    await cfg.update(key, value, vscode.ConfigurationTarget.Global);
  }
  vscode.window.showInformationMessage("Neon Terminal 2030: recommended editor settings applied.");
}

async function applyVariant(themeId) {
  await vscode.workspace
    .getConfiguration()
    .update("workbench.colorTheme", themeId, vscode.ConfigurationTarget.Global);
}

async function enableGlow(context, opts) {
  const customCss = vscode.extensions.getExtension(CUSTOM_CSS_EXT);
  if (!customCss) {
    const pick = await vscode.window.showWarningMessage(
      'Glow needs the "Custom CSS and JS Loader" extension. Install it now?',
      "Install",
      "Cancel"
    );
    if (pick === "Install") {
      await vscode.commands.executeCommand("workbench.extensions.installExtension", CUSTOM_CSS_EXT);
    }
    return false;
  }

  // Write the tuned stylesheet into global storage.
  fs.mkdirSync(context.globalStorageUri.fsPath, { recursive: true });
  const cssPath = glowCssPath(context);
  fs.writeFileSync(cssPath, generateGlowCss(opts), "utf8");

  // Point Custom CSS at it (preserve any existing imports).
  const cfg = vscode.workspace.getConfiguration();
  const importUri = vscode.Uri.file(cssPath).toString();
  const current = cfg.get("vscode_custom_css.imports") || [];
  const others = current.filter((u) => !u.includes("neon-glow"));
  await cfg.update(
    "vscode_custom_css.imports",
    [...others, importUri],
    vscode.ConfigurationTarget.Global
  );

  const pick = await vscode.window.showInformationMessage(
    "Neon glow written. Run “Reload Custom CSS and JS”, then restart VS Code to see it.",
    "Reload Now"
  );
  if (pick === "Reload Now") {
    await vscode.commands.executeCommand("extension.updateCustomCSS");
  }
  return true;
}

async function disableGlow(context) {
  const cfg = vscode.workspace.getConfiguration();
  const current = cfg.get("vscode_custom_css.imports") || [];
  await cfg.update(
    "vscode_custom_css.imports",
    current.filter((u) => !u.includes("neon-glow")),
    vscode.ConfigurationTarget.Global
  );
  const cssPath = glowCssPath(context);
  if (fs.existsSync(cssPath)) fs.rmSync(cssPath);
  const pick = await vscode.window.showInformationMessage(
    "Neon glow disabled. Reload Custom CSS and restart to fully remove it.",
    "Reload Now"
  );
  if (pick === "Reload Now") {
    await vscode.commands.executeCommand("extension.updateCustomCSS");
  }
}

function currentState(context) {
  const cfg = vscode.workspace.getConfiguration();
  const imports = cfg.get("vscode_custom_css.imports") || [];
  return {
    theme: cfg.get("workbench.colorTheme"),
    glowOn: imports.some((u) => u.includes("neon-glow")),
    customCssInstalled: !!vscode.extensions.getExtension(CUSTOM_CSS_EXT),
    variants: VARIANTS,
    accents: ACCENTS,
  };
}

function getWebviewHtml(state) {
  const variantBtns = state.variants
    .map(
      (v) =>
        `<button class="variant" data-id="${v.id}" ${
          state.theme === v.id ? 'data-active="1"' : ""
        }><span class="sw" style="background:${v.swatch}"></span>${v.label}</button>`
    )
    .join("");
  const accentBtns = state.accents
    .map(
      (a) =>
        `<button class="accent" data-id="${a.id}" title="${a.label}" style="--c:${a.color}"></button>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';" />
<style>
  :root {
    --bg:#0A0D14; --panel:#0D1119; --line:#1A2030; --fg:#C6D2E2;
    --mint:#34F5C5; --magenta:#FF4D9D; --muted:#7A88A0;
  }
  * { box-sizing:border-box; }
  body {
    margin:0; padding:28px 26px 40px; background:var(--bg); color:var(--fg);
    font-family:"JetBrains Mono","Fira Code",ui-monospace,Menlo,Consolas,monospace;
    font-size:13px; line-height:1.55;
  }
  h1 {
    font-size:18px; margin:0 0 2px; letter-spacing:.5px;
    color:var(--mint); text-shadow:0 0 14px #34F5C566;
  }
  .sub { color:var(--muted); margin:0 0 26px; font-size:12px; }
  .card {
    background:var(--panel); border:1px solid var(--line); border-radius:12px;
    padding:18px 18px 20px; margin-bottom:18px;
  }
  .card h2 { font-size:12px; text-transform:uppercase; letter-spacing:1.5px;
    color:var(--magenta); margin:0 0 14px; }
  .row { display:flex; align-items:center; gap:12px; flex-wrap:wrap; }
  button {
    font-family:inherit; font-size:12.5px; cursor:pointer;
    background:#11151F; color:var(--fg); border:1px solid var(--line);
    border-radius:8px; padding:9px 14px; transition:all .15s;
  }
  button:hover { border-color:var(--mint); color:var(--mint); }
  .variant { display:flex; align-items:center; gap:9px; }
  .variant[data-active="1"] { border-color:var(--mint); color:var(--mint);
    box-shadow:0 0 0 1px var(--mint), 0 0 18px -6px var(--mint); }
  .sw { width:14px; height:14px; border-radius:4px; border:1px solid #ffffff22; }
  .primary { background:var(--mint); color:#06221C; border-color:var(--mint); font-weight:600; }
  .primary:hover { background:#5EFFD7; color:#06221C; }
  .accent { width:26px; height:26px; border-radius:50%; padding:0; border:2px solid #ffffff22;
    background:var(--c); box-shadow:0 0 10px -2px var(--c); }
  .accent[data-active="1"] { border-color:#fff; transform:scale(1.12); }
  .switch { display:flex; align-items:center; gap:12px; }
  .toggle { width:48px; height:26px; border-radius:14px; background:#11151F; border:1px solid var(--line);
    position:relative; cursor:pointer; transition:all .2s; flex:none; }
  .toggle::after { content:""; position:absolute; top:2px; left:2px; width:20px; height:20px;
    border-radius:50%; background:var(--muted); transition:all .2s; }
  .toggle[data-on="1"] { background:#34F5C522; border-color:var(--mint); }
  .toggle[data-on="1"]::after { left:24px; background:var(--mint); box-shadow:0 0 10px var(--mint); }
  .slider-wrap { margin-top:14px; }
  label.k { color:var(--muted); font-size:11.5px; display:block; margin-bottom:6px; }
  input[type=range] { width:100%; accent-color:var(--mint); }
  .hint { color:var(--muted); font-size:11px; margin-top:10px; }
  .warn { color:#FFB84D; }
  .disabled { opacity:.45; pointer-events:none; }
</style>
</head>
<body>
  <h1>⚡ Neon Terminal 2030</h1>
  <p class="sub">Tune your 2030 terminal. Changes apply to your global settings.</p>

  <div class="card">
    <h2>Theme variant</h2>
    <div class="row">${variantBtns}</div>
  </div>

  <div class="card">
    <h2>Recommended setup</h2>
    <div class="row">
      <button class="primary" id="applyRec">Apply recommended editor settings</button>
    </div>
    <p class="hint">Bracket colors · semantic highlight · ligatures · sticky scroll · inlay hints · smooth caret.</p>
  </div>

  <div class="card" id="glowCard">
    <h2>Neon glow add-on</h2>
    <div class="switch">
      <div class="toggle" id="glowToggle" data-on="${state.glowOn ? 1 : 0}"></div>
      <span>Enable real neon bloom &amp; cursor pulse</span>
    </div>
    <div id="glowControls" class="${state.glowOn ? "" : "disabled"}">
      <div class="slider-wrap">
        <label class="k">Glow strength — <span id="strVal">0.55</span></label>
        <input type="range" id="strength" min="0" max="1" step="0.05" value="0.55" />
      </div>
      <div class="slider-wrap">
        <label class="k">Bloom radius — <span id="radVal">6</span>px</label>
        <input type="range" id="radius" min="2" max="16" step="1" value="6" />
      </div>
      <div class="slider-wrap">
        <label class="k">Accent color</label>
        <div class="row" id="accentRow">${accentBtns}</div>
      </div>
      <button class="primary" id="applyGlow" style="margin-top:16px">Apply glow</button>
    </div>
    <p class="hint ${state.customCssInstalled ? "" : "warn"}">
      ${
        state.customCssInstalled
          ? "Requires reloading Custom CSS + a window restart to take effect."
          : "⚠ Needs the “Custom CSS and JS Loader” extension — you’ll be prompted to install it."
      }
    </p>
  </div>

<script>
  const vscode = acquireVsCodeApi();
  let accent = "mint";

  document.querySelectorAll(".variant").forEach(b =>
    b.addEventListener("click", () => {
      document.querySelectorAll(".variant").forEach(x => x.removeAttribute("data-active"));
      b.setAttribute("data-active","1");
      vscode.postMessage({ type:"variant", id:b.dataset.id });
    }));

  document.getElementById("applyRec").addEventListener("click", () =>
    vscode.postMessage({ type:"recommended" }));

  const toggle = document.getElementById("glowToggle");
  const controls = document.getElementById("glowControls");
  toggle.addEventListener("click", () => {
    const on = toggle.dataset.on === "1" ? 0 : 1;
    toggle.dataset.on = on;
    controls.className = on ? "" : "disabled";
    vscode.postMessage({ type: on ? "glowOn" : "glowOff", ...readGlow() });
  });

  const strength = document.getElementById("strength");
  const radius = document.getElementById("radius");
  strength.addEventListener("input", () => document.getElementById("strVal").textContent = strength.value);
  radius.addEventListener("input", () => document.getElementById("radVal").textContent = radius.value);

  document.querySelectorAll(".accent").forEach(a =>
    a.addEventListener("click", () => {
      document.querySelectorAll(".accent").forEach(x => x.removeAttribute("data-active"));
      a.setAttribute("data-active","1");
      accent = a.dataset.id;
    }));

  function readGlow(){ return { strength: parseFloat(strength.value), radius: parseInt(radius.value), accent }; }
  document.getElementById("applyGlow").addEventListener("click", () =>
    vscode.postMessage({ type:"glowOn", ...readGlow() }));
</script>
</body>
</html>`;
}

function openPanel(context) {
  const panel = vscode.window.createWebviewPanel(
    "neonTerminal2030.settings",
    "Neon Terminal 2030",
    vscode.ViewColumn.Active,
    { enableScripts: true, retainContextWhenHidden: true }
  );
  panel.webview.html = getWebviewHtml(currentState(context));

  panel.webview.onDidReceiveMessage(async (msg) => {
    switch (msg.type) {
      case "variant":
        await applyVariant(msg.id);
        break;
      case "recommended":
        await applyRecommended();
        break;
      case "glowOn":
        await enableGlow(context, { strength: msg.strength, radius: msg.radius, accent: msg.accent });
        break;
      case "glowOff":
        await disableGlow(context);
        break;
    }
  });
}

function activate(context) {
  context.subscriptions.push(
    vscode.commands.registerCommand("neonTerminal2030.openSettings", () => openPanel(context)),
    vscode.commands.registerCommand("neonTerminal2030.applyRecommended", () => applyRecommended()),
    vscode.commands.registerCommand("neonTerminal2030.toggleGlow", async () => {
      const on = (vscode.workspace.getConfiguration().get("vscode_custom_css.imports") || []).some(
        (u) => u.includes("neon-glow")
      );
      if (on) await disableGlow(context);
      else await enableGlow(context, { strength: 0.55, radius: 6, accent: "mint" });
    })
  );
}

function deactivate() {}

module.exports = { activate, deactivate };
